[package]
name = "terminal-supports-emoji"
description = "Check whether the current terminal supports emoji"
license = "Apache-2.0 OR MIT"
repository = ""
version = "0.1.0"
authors = ["SirWindfield <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
atty = "0.2.14"
